package corejava.collections;

import java.util.HashMap;
import java.util.IdentityHashMap;
import java.util.LinkedHashMap;
import java.util.Map;

public class IdentityHashMapPractice {

    public static void main(String[] args) {

        Map<String, Integer> map = new HashMap<>();

        String key1 = new String("key");
        String key2 = new String("key");

        map.put(key1, 1);
        map.put(key2, 2);

        System.out.println(map); // gives one values because old is overridden by new one

        // Now Use an IdentityHashMap
        Map<String, Integer> identity = new IdentityHashMap<>();

        identity.put(key1, 1);
        identity.put(key2, 2);

        System.out.println(identity); // gives both values, because hashCode generated by Memory Address not by Key's value

        // gives same HashCode because values are same
        System.out.println(key1.hashCode());
        System.out.println(key2.hashCode());

        // gives different HashCode because Addresses are different, this used by IdentityHashMap
        System.out.println(System.identityHashCode(key1));
        System.out.println(System.identityHashCode(key2));

    }
}
